### ISSUE TITLE
How to access state after effects complete in middleware?

### ISSUE THREAD

**Issue by JoeZheng2015** [FormidableLabs/freactal#62] opened 2017-06-19 14:17 UTC
In freactal v1.1.0, I want to track the state changes in middleware for debugging just like what [redux-logger](https://github.com/evgenyrodionov/redux-logger) did. However I find that I can't access the latest state after effects complete in middleware.

Am I missing anything? And it would be fabulous if you could help me out. Thanks!

**Comment by divmain** [comment] 2017-06-20 06:58
Hi @JoeZheng2015!  Thanks for opening the PR!  I've merged in the changes (which was my intended behavior, anyway :) ), and they'll be included in the next release!

**Closed by divmain** 2017-06-20 06:58 UTC

**Comment by JoeZheng2015** [comment] 2017-06-20 07:14
@divmain Thanks :)
