### ISSUE TITLE
webpack HMR

### ISSUE THREAD

**Issue by Piliponful** [FormidableLabs/freactal#65] opened 2017-06-25 18:29 UTC
Was there any discussions on that topic. Do you have any documentation or something? I was thinking it would work out of the box with just react-hot-loader and sadly enough it didn't. You can check out the code here and try run it yourself - https://github.com/Piliponful/react-starter/tree/freactal

**Comment by jcrben** [comment] 2017-06-29 05:02
Did you see https://github.com/FormidableLabs/freactal/issues/27?

**Comment by Piliponful** [comment] 2017-06-29 05:40
> Did you see #27?
No i didn't. Thanks. I will look into it.

**Comment by jcrben** [comment] 2017-06-29 05:49
Perhaps you could go ahead and close this as a duplicate of https://github.com/FormidableLabs/freactal/issues/27

Note that `react-hot-loader` has some inherent limitations.

**Comment by divmain** [comment] 2017-06-29 06:46
Thanks @jcrben!  Closing this as a dupe.

If I get around to it, one of the TODO projects in my OSS queue is a more comprehensive hot-reload transform.  Then again, I may just build it into [Interlock](http://interlockjs.com) if I ever get around to finishing it.

Anyway, thanks!  And sorry for the HMR frustrations.  Would fix if I could.

**Closed by divmain** 2017-06-29 06:46 UTC
